### ISSUE TITLE
resume fails due to FileAlreadyExistsException

### ISSUE THREAD

**Issue by koadman** [cerebis/meta-sweeper#16]
When a running workflow is interrupted and then later resumed with the -resume option it appears to fail.

**Comment by cerebis** [comment]
I've had a look at this. Nextflow's handling of the scenario might not be your first guess.

When the Process publishDir directive is set to not overwrite files (`overwrite: "false"`), an exception is thrown if the file already exists. I would have perhaps thought it would just not overwrite the file and continue!

Anyway, if you change this to `overwrite: "true"` you will still get an exception thrown for symlink output. 

Using symlinks in the publish directory is preferable to copy/move as it saves space and maintains resume-ability. 

**Still** It turns out that the current release of Nextflow (0.18) cannot remove a symlink. I've added a method which will correctly remove a symlink and adjusted the code accordingly. This will require using my forked release build.

**Comment by koadman** [comment]
I wonder if the symlinking of output files may be a false economy. The issue is that, at least when developing and debugging, I end up with many data directories in work/\* that have randomized temp file names, and which can take up a lot of space, but I am unsure which ones pertain to failed or unwanted runs and are therefore safe to delete. Is there another way to remove only work files associated with a particular run, rather than `rm -rf work/*`? I wonder if it might be more practical to just copy files to the output directory and continue with `rm -rf work/*`.

**Comment by cerebis** [comment]
Ya, the flat structure of the Nextflow work directory is lacking when it comes to looking around within it.

You can manually specify the work directory however `-w` or `--work-dir`.

**Comment by cerebis** [comment]
Deleting work though, would mean you sacrifice any ability to resume a job.

**Comment by cerebis** [comment]
This is going to stay open but the original issue has been resolved in my fork of Nextflow

http://github.com/cerebis/nextflow/releases/tag/pbspro_0.2
